# packet_folder,label,role,paired_app

stun_a,STUN_Allocate,baseline,

whatsapp_a_vo,WhatsApp,normal,whatsapp_a_vo_randomattr
whatsapp_a_vo_randomattr,WhatsApp_Modified,modified,whatsapp_a_vo

telegram_a_u,Telegram,normal,telegram_a_u_randomrealm
telegram_a_u_randomrealm,Telegram_Modified,modified,telegram_a_u

signal_a_u,Signal,normal,signal_a_u_randomrealm
signal_a_u_randomrealm,Signal_Modified,modified,signal_a_u

messenger_a_u,Messenger,normal,messenger_a_u_randomrealm
messenger_a_u_randomrealm,Messenger_Modified,modified,messenger_a_u